export const REQUESTJOB_REQUEST = "REQUESTJOB_REQUEST";
export const REQUESTJOB_SUCCESS = "REQUESTJOB_SUCCESS";
export const REQUESTJOB_FAIL = "REQUESTJOB_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_MESSAGE = "SET_MESSAGE";
