// UserDataModel.js

const UserDataModel = {

  UserBioDetails: {
    cv_path: "",
    initial: "",
    initial_name: "",
    permanent_address: "",
    contact_address: "",
    mobile: "",
    mobile_2: "",
    email: "",
    dob: "",
    age: "",
    marital_status: "",
    Password: "",
    gender: "",
    nationality: "",
    nic_passport: "",
    police_station: "",
    electorate: "",
    district: "",
    activities: "",
    extracurricular_activities: "",
    ol_year: "",
    ol_school: "",
    ol_index: "",
    al_year: "",
    al_school: "",
    al_index: "",
    technical_skills: "",
    training_programmes: "",
    membership: "",
    sinhala_level: "",
    tamil_level: "",
    english_level: "",
    career_objective: "",
    aspirations: "",
    relatives: "",
    previously_worked: "",
    court_cases: "",
    suspension_fromwork: "",
    illneses: "",
    other_information: "",
    referee_name1: "",
    referee_designation1: "",
    referee_address1: "",
    referee_mobile1: "",
    referee_mobileextra1: "",
    referee_email1: "",
    referee_name2: "",
    referee_designation2: "",
    referee_address2: "",
    referee_mobile2: "",
    referee_mobileextra2: "",
    referee_email2: "",
    passport: "",
    ol_result: "",
    al_result: "",
    sports: "",
    projects: "",
    computer_literacy: "",
    CvFile: "",
  },
};

const HigherEducationalDataModel = {
  from_year: "",
  to_year: "",
  institution: "",
  degree: "",
  grade: "",
  area: "",
  reg_userid: "",
  biodata_id: "",
  higher_educational_id: "",
};

const ProfessionalDetailsDataModel = {
  prof_qualification_id: "",
  biodata_id: "",
  reg_userid: "",
  qualification_name: "",
  category: "",
  level: "",
  nvq: "",
  completed_year: "",
};

const EmplyeeDetailsDataModel = {
  employeedetails_id: "",
  biodata_id: "",
  reg_userid: "",
  employer_name: "",
  designation: "",
  employer_address: "",
  superior_name: "",
  superior_designation: "",
  superior_contactno: "",
  form_year: "",
  to_year: "",
};

export {
  UserDataModel,
  HigherEducationalDataModel,
  ProfessionalDetailsDataModel,
  EmplyeeDetailsDataModel,
};
