export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAIL = "GET_DATA_FAIL";

export const GET_DATA1_REQUEST = "GET_DATA1_REQUEST";
export const GET_DATA1_SUCCESS = "GET_DATA1__SUCCESS";
export const GET_DATA1_FAIL = "GET_DATA1_FAIL";

export const GET_DATA2_REQUEST = "GET_DATA2_REQUEST";
export const GET_DATA2_SUCCESS = "GET_DATA2_SUCCESS";
export const GET_DATA2_FAIL = "GET_DATA2_FAIL";

export const GET_DATA3_REQUEST = "GET_DATA3REQUEST";
export const GET_DATA3_SUCCESS = "GET_DATA3SUCCESS";
export const GET_DATA3_FAIL = "GET_DATA3FAIL";
